# Deployment for updating PODS & REPLICASETS
apiVersion: apps/v1
kind: Deployment
metadata:
    name: login
spec:
    replicas: 1
    selector:
      matchLabels:
        app: login
    template:
      metadata:
        labels:
          app: login
    spec:
      containers:
      - name: login
        image: kalyangali12/login2501:1.1
        ports:
        - containerPort: 80
