# Deployment for updating PODS & REPLICASETS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:  # <--- Make sure "spec" is here, NOT "spec.spec"
      containers:
        - name: my-container
          image: kalyangali12/login-2501:2.1
          ports:
            - containerPort: 80
