# create multi container pod
apiVersion: v1  
kind: Pod 
metadata:  
  name: multi-pod-fail 
spec: 
  container: 
  - name: c1
    image: nginx
    Ports: 
    - container: 80
  - name: c2
    image: nginx
    Ports: 
    - container: 80