# Create Multi Container Pod
# Create Multi Container Pod -1
# Create Multi Container Pod -2
# Create Multi Container Pod -3

apiVersion: v1  
kind: Pod 
metadata: 
  name: multi-pod-fail 
spec: 
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80

    - name: c2
      image: nginx
      ports:
        - containerPort: 80
