# Create Nginx Pod
# kubectl run nginx-pod --image nginx --port=80
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80

