# Create Nginx Pod
# Kubectl run nginx-pod --image nginx --port=80
apiVersion: v1 # key: value
kind: Pod # key: value
metadata: # dictionary
  name: nginx-pod
spec: # dictionary
  container: # list
  -name: C1
  image: nginx
  ports: 
  - container: 80