# Service Template with NodePort
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: Myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
